overview: adding the CSI definition
confidential-containers/documentation pull request #123
Opened 2023-05-24 21:20 UTC by beraldoleal

Just introducing the definition for 'CSI', which I'm assuming is about 'Container Storage Interface'. This acronym was previously used in the document without any introduction or explanation. This change will help readers who are not familiar with the term to better understand the content.

2023-05-25 09:57 UTC, c3d commented on overview.md
> +other areas of the cloud native stack, from container runtime to Container Orchestration Interface
```suggestion
other areas of the cloud native stack, from container runtime to [Container Storage Interface](https://github.com/confidential-containers/documentation/wiki/Glossary#container-storage-interface)
````

2023-05-25 09:57 UTC, c3d requested changes
Typo, you wrote "Orchestration" instead of "Storage"

2023-05-25 14:14 UTC, beraldoleal commented
Thank you @c3d , for some reason I replaced with Orchestration. :/ Fixed and added the link.

2023-06-08 14:27 UTC, magowan approved these changes
Change looks good to me thanks

2023-06-08 14:28 UTC, magowan commented
@c3d are you good to approve?
Thanks

2023-07-20 18:51 UTC, magowan commented
This PR will need to be re-created against https://github.com/confidential-containers/confidential-containers as we have merged this repo into there.

2023-07-20 18:55 UTC, closed without merging